### ISSUE TITLE
[WIP] Evaluation Question 5

### ISSUE THREAD

**Issue by don-tnowe** [oleksandrblazhko/ai-192-krupenov#12]
# Запитання No1
>В лабораторній роботі No5 вами було розглянуто декілька описів тестів з документу
>OWASP Web Security Testing Guide.
>Для кожного тесту вкажіть, з якими вразливостями OWASP Top 10 версії 2021 року
>тест пов’язано - https://owasp.org/Top10/

# Запитання No 2
>В лабораторній роботі No6 вами було розглянуто приклади вимог до безпечного ПЗ
>з документу OWASP Application Security Verification Standard.
>Для кожного розглянутого підрозділу вимог вкажіть, з якими вразливостями OWASP
>Top 10 версії 2021 року цей підрозділ пов’язано https://owasp.org/Top10/

# Запитання No3
>В описах вразливостей OWASP Top 10 версії 2021 року є підрозділ «Example Attack
>Scenarios». Візміть одну вразливість, розглянуту в попередніх рішеннях, та, аналізуючи
>опис «Example Attack Scenarios», запропонуйте три тестові сценарії перевірки наявності
>вразливості.
>Кожний тестовий сценарій повинен містити:
>1) окремий розділ з описом дій (кроків) тестувальника, які дозволяють перевірити
>на наявність вразливості у форматі, наприклад, крок 1 – опис ..., крок 2 – опис ...
>2) опис очікуємого результату, який підтверджує наявність вразливлості.

**Comment by oleksandrblazhko** [comment]
Не побачів ваші рішення!
