### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-192-krupenov#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
4) Відомо, що з серпня 2021 року GitHub-сервер замінив класичний процес 
аутентифікації через пароль на процес з використанням Token 
під час безпечного оновлення GitHub-репозиторію. 
Поясніть, будь ласка, чому так було зроблено?

**Comment by don-tnowe** [comment]
Токени автентифікації GitHub більш безпечні за паролі, оскільки кожному токену можна налаштувати дозволи: під пристрій чи на одне використання, та під різні операції.

Вони також завжди генеруються автоматично, тому їх складніше отримати підбором; а також вони не можуть бути використані поза GitHub. Також можна вилучити токен в будь-який час, щоб припинити доступ лише до того, що захищає саме цей токен.

**Comment by oleksandrblazhko** [comment]
оцінка = 2 бали
